import os
import time

def clrscr():
    os.system('cls')
    print("\n\n")
    time.sleep(2)

def slowprint(x):
    for letter in x:
        print(letter, end="", flush=True)
        time.sleep(.5)

def fastprint(x):
    for letter in x:
        print(letter, end="", flush=True)
        time.sleep(.1)

pnum = "5555069"
search = "SEARCHING  ......................................................"
batch = "FILE FOUND  ..............."
pload = "EXTRACTING DATA  .............................."
#compile = "COMPILING  |||||||||||||||||||||||||"
error = "ERROR"
reint = "REINITIALIZING  .................."
matrix = "The Matrix has you..."
follow = "Follow the.............."

clrscr()
user = input("Login: ")
wake = "Wake up, "+user+"."
clrscr()
slowprint(pnum)
clrscr()
fastprint(search)
print("\n\n")
fastprint(batch)
print("\n\n")
fastprint(pload)
print("\n\n")
time.sleep(2)
#fastprint(compile)
#print("\n\n")
#fastprint(error)
#print("\n")
fastprint(error)
clrscr()
time.sleep(2)
fastprint(reint)
time.sleep(2)
clrscr()
fastprint(error)
time.sleep(2)
clrscr()
time.sleep(3)
fastprint(wake)
time.sleep(3)
clrscr()
time.sleep(1)
fastprint(matrix)
time.sleep(3)
clrscr()
time.sleep(1)
fastprint(follow)
os.system('cls')


print(".                                                                              .")
time.sleep(.5)
print(".                                                                              .")
time.sleep(.5)
print(".                                                                              .")
time.sleep(.5)
print(".                                                                              .")
time.sleep(.5)
print(".                                                                              .")
time.sleep(.5)
print(".                                                                              .")
time.sleep(.5)
print(".                                                                              .")
time.sleep(.5)
print(".                                                                              .")
time.sleep(.5)
print(".                                                                              .")
time.sleep(.5)
print(".                                        @@   @                                .")
time.sleep(.5)
print(".                                        @@@@ @@                               .")
time.sleep(.5)
print(".                                        @@@@@ @@                              .")
time.sleep(.5)
print(".                                          @@@ @@                              .")
time.sleep(.5)
print(".                                           @@@@@@@@@                          .")
time.sleep(.5)
print(".                                           @@@@@@ @@@                         .")
time.sleep(.5)
print(".                                         @@@@@@@@@@@@@@                       .")
time.sleep(.5)
print(".                            @@@@@@@@@@@@@@@@@@@@@@@@@@@                       .")
time.sleep(.5)
print(".                         @@@@@@@@@@@@@@@@@@@@@@@@@                            .")
time.sleep(.5)
print(".                        @@@ @@@@@@ @@@@@@@@@@@@@@@                            .")
time.sleep(.5)
print(".                       @@@@@@@@@@@@@ @@@@@@@@@@@                              .")
time.sleep(.5)
print(".                       @@@@@@@@@@@@@ @@@@@@@@@@@@@                            .")
time.sleep(.5)
print(".                        @@@@@@@@@@@ @@@@@@@@@@@                               .")
time.sleep(.5)
print(".                         @@@@@@@@@@@ @@@@@ @@@@@@                             .")
time.sleep(.5)
print(".                               @@@@@@@@                                       .")
time.sleep(.5)
print(".                                                                              .")
time.sleep(.5)
print(".                                                                              .")
time.sleep(.5)
print(".                                                                              .")
time.sleep(.5)
print(".                                                                              .")
time.sleep(.5)
print(".                                                                              .")
time.sleep(.5)
print(".                                                                              .")
time.sleep(.5)
print(".                                                                              .")
time.sleep(.5)
print(".                                                                              .")
print("\n\n")
